version: '2'
services:

  server:
    build: .
    ports:
      - "127.0.0.1:9009:9000"
    restart: always
    volumes:
      - "./data/conf:/usr/local/leanote/conf/"
      - "./data/files:/usr/local/leanote/files"
      - "./data/upload:/usr/local/leanote/public/upload"
    links:
      - db:db
    depends_on:
      - db

  db:
    image: "mongo:3"
    restart: always
    volumes:
      - "./data/mongo:/data/db"
