server:
  build: .
  ports:
    - "9009:9000"
  restart: always
  volumes:
    - "/data/leanote/conf:/usr/local/leanote/conf/"
    - "/data/leanote/files:/usr/local/leanote/files"
  links:
    - db

db:
  image: "mongo:3.2.3"
  volumes:
    - "/data/leanote/mongo:/data/db"
  ports:
    - "27017:27017"
